name: Push the Docker image

on:
  push:
    branches: [new_ci]
  pull_request:
    branches: [new_ci]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker logout
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the app
        run: |
          export FLASK_ENV=development
          export FLASK_APP=application.py
          pip install flask
          python application.py &
          python test_application.py

  publish:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: checkout
      - run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build . -t ${{ secrets.DOCKER_USERNAME }}/apifilmproject:tagname
          docker image push ${{ secrets.DOCKER_USERNAME }}/apifilmproject:tagname
