name: Push the Docker image

on:
  push:
    branches: [new_ci]
  pull_request:
    branches: [new_ci]

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test the app
        run: |
          export FLASK_ENV=development
          export FLASK_APP=application.py
          pip install flask
          python application.py &
          python test_application.py

  build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: Log in to Docker Hub
          env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          run: |
            docker logout
            docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
            docker build . -t $DOCKER_LOGIN/apifilmproject:tagname
            docker image push $DOCKER_LOGIN/apifilmproject:tagname
  
