name: Push the Docker image

on:
  push:
    branches: [new_ci]
  pull_request:
    branches: [new_ci]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Run du container
        run: |
          export FLASK_ENV=development
          export FLASK_APP=application.py
          pip install flask
          python application.py &
          python test_application.py

      - name: Build and Push into Docker Hub
        run: |
          docker build --tag apifilmproject .
          docker push mehdidi13/apifilmproject
